# Generated by Django 5.2.17 on 2026-09-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatikMotif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('asal', models.CharField(choices=[('YOGYAKARTA', 'Yogyakarta'), ('SOLO', 'Solo'), ('PEKALONGAN', 'Pekalongan'), ('BANYUMAS', 'Banyumas'), ('LASEM', 'Lasem'), ('SEMARANG', 'Semarang'), ('DEMAK', 'Demak'), ('KUDUS', 'Kudus'), ('JEPARA', 'Jepara'), ('PATI', 'Pati'), ('REMBANG', 'Rembang'), ('WONOSOBO', 'Wonosobo'), ('KLATEN', 'Klaten'), ('SRAGEN', 'Sragen'), ('MAGELANG', 'Magelang'), ('TEGAL', 'Tegal'), ('BREBES', 'Brebes'), ('BATANG', 'Batang'), ('CIREBON', 'Cirebon'), ('GARUT', 'Garut'), ('TASIKMALAYA', 'Tasikmalaya'), ('INDRAMAYU', 'Indramayu'), ('BANDUNG', 'Bandung'), ('SUMEDANG', 'Sumedang'), ('SUBANG', 'Subang'), ('CIAMIS', 'Ciamis'), ('BANTEN', 'Banten'), ('LEBAK', 'Lebak'), ('TANGERANG', 'Tangerang'), ('MADURA', 'Madura'), ('TUBAN', 'Tuban'), ('LAMONGAN', 'Lamongan'), ('SIDOARJO', 'Sidoarjo'), ('MOJOKERTO', 'Mojokerto'), ('KEDIRI', 'Kediri'), ('MALANG', 'Malang'), ('PONOROGO', 'Ponorogo'), ('TULUNGAGUNG', 'Tulungagung'), ('BANYUWANGI', 'Banyuwangi'), ('JEMBER', 'Jember'), ('BLITAR', 'Blitar'), ('BOJONEGORO', 'Bojonegoro'), ('PASURUAN', 'Pasuruan'), ('PROBOLINGGO', 'Probolinggo'), ('BALI', 'Bali'), ('LOMBOK', 'Lombok'), ('SUMBA', 'Sumba'), ('FLORES', 'Flores'), ('ACEH', 'Aceh'), ('JAMBI', 'Jambi'), ('PALEMBANG', 'Palembang'), ('BENGKULU', 'Bengkulu'), ('LAMPUNG', 'Lampung'), ('RIAU', 'Riau'), ('BANGKA_BELITUNG', 'Bangka Belitung'), ('KALIMANTAN_BARAT', 'Kalimantan Barat'), ('KALIMANTAN_SELATAN', 'Kalimantan Selatan'), ('KALIMANTAN_TIMUR', 'Kalimantan Timur'), ('SULAWESI_UTARA', 'Sulawesi Utara'), ('SULAWESI_TENGAH', 'Sulawesi Tengah'), ('SULAWESI_SELATAN', 'Sulawesi Selatan'), ('SULAWESI_TENGGARA', 'Sulawesi Tenggara'), ('MALUKU', 'Maluku')], max_length=300)),
                ('filosofi', models.TextField()),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='batik')),
            ],
        ),
    ]
