# Generated by Django 5.2.17 on 2026-09-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_batikmotif_favorit_alter_batikmotif_asal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batikmotif',
            name='favorit',
        ),
    ]
